### ISSUE TITLE
中括号里的数字是提交答案的数量吗？

### ISSUE THREAD

**Issue by yaoshanliang** [sundy-li/wechat_brain#1]

**Comment by sundy-li** [comment]
不是的, 是搜索引擎API结果包含 选型的次数
1. 已经做过的题目会自动存入数据库, 下次出现后显示 [标准答案]
2. 未做过的题目,通过搜索引擎API来做个统计概率显示,一定程度提高正确性

**Comment by qwertccc** [comment]
@sundy-li 如果程序提供的答案是错的，或者说没有提供答案，但是我手动答对了，会记录到哪里？如何反馈给你添加到你的主库里？

**Comment by sundy-li** [comment]
每次回答都会记录在 questions.data文件中,  我会做一个合并工具来合并题库.

**Comment by sundy-li** [comment]
#9
