### ISSUE TITLE
标准错误答案

### ISSUE THREAD

**Issue by AdonisGe** [sundy-li/wechat_brain#10]
用你云服务器上的代理，玩了不到一个小时遇到两个标准答案错误的了。。
想知道代码里面有没有更新已有标准答案的逻辑，如果没有这几道题目就要一直错下去了

**Comment by lonee8** [comment]
我是下载在自己电脑上用的，也有这样的问题。
但我猜是可以更正的。

**Comment by sundy-li** [comment]
可能是官方发现答案错了,然后更正了. 
这个工具是会自动更正的, 每次题目都会以最新答案存入数据库文件中.
