### ISSUE TITLE
Linux版怎么使用

### ISSUE THREAD

**Issue by Jiangzelong** [sundy-li/wechat_brain#12]
$ ls -al
    -rwxrw-r-x  1 fire fire 5257536 Dec 31  1979 brain
    -rw-rw-r--  1 fire fire  262144 Jan 11 18:29 questions.data
    -rw-rw-r--  1 fire fire     708 Dec 31  1979 README.md

$ brain
    usage: brain [infile] [outfile] [dim1 dim2 dim3] [pottsweight]

这里没看懂要怎么设置。。。

**Comment by sundy-li** [comment]
./brain 就行了

**Comment by Jiangzelong** [comment]
可以了，谢谢
