### ISSUE TITLE
关于合并题库的建议

### ISSUE THREAD

**Issue by lonee8** [sundy-li/wechat_brain#14]
题库收录时候，有没有加收录时间？
合并时候，相同题目，答案应该以时间新的为准，因为官方有时候也改答案啊。

**Comment by sundy-li** [comment]
我看了下题库接口没有返回时间, 不好弄这个..

**Comment by lonee8** [comment]
取本地时间也可以吧，电脑上的时间一般不会误差太多。

**Comment by sundy-li** [comment]
![image](https://user-images.githubusercontent.com/3325189/34860283-5eedc278-f797-11e7-9afd-2c4f86bf7449.png)

这题库有点蛋疼...

**Comment by lonee8** [comment]
比这蛋疼的多了。
没办法。
今天用了合并题库，发现改标准答案的好几个。

**Comment by sundy-li** [comment]
#17

**Comment by zxc135781** [comment]
测试发现标准答案错了好多

**Comment by sundy-li** [comment]
采用了 @lonee8  的建议, 新版本增加了最后更新时间字段

**Comment by czd99053** [comment]
[questions.zip](https://github.com/sundy-li/wechat_brain/files/1898717/questions.zip)
