### ISSUE TITLE
怎么在安卓系统里安装goproxy.crt？

### ISSUE THREAD

**Issue by plike85** [sundy-li/wechat_brain#15]
怎么在安卓系统里安装goproxy.crt？
安全->从SD卡安装证书，提示是无效证书

**Comment by zywzlj** [comment]
华为P9和三星S5都提示“没有可安装的证书”。

**Comment by sundy-li** [comment]
发到手机上, 文件管理那里打开就可以了
(我是发到自己微信, 微信打开后就可以了)

**Comment by jstony** [comment]
华为手机，安装证书的时候提示无法安装该证书，也是发送给自己的微信然后打开。

**Comment by jstony** [comment]
是不是还需要有个根证书先安装并信任一下？

**Comment by lonee8** [comment]
最简单就是用系统浏览器访问这个证书就好了。

**Comment by plike85** [comment]
用你的方法可以搞定，多谢

**Comment by zywzlj** [comment]
怎么用系统浏览器访问证书哇，下载证书没法用浏览器打开
