### ISSUE TITLE
IOS，提示：1  

### ISSUE THREAD

**Issue by kingmo888** [sundy-li/wechat_brain#16]
提问之前,请务必带有以下信息,不接受非技术性issue

1. 你运行的代码命令,你的操作是什么
基于go环境的run,      Win7
2. 你的客户端操作系统, 微信版本, 是否添加成功证书
IOS11 微信IOS最新版，证书添加成功（安装后，到设置-关于本机-证书那里信任一下）
3. 执行的结果是什么
主界面刷新会显示 提示：1，进入二级界面（答题段位）提示网络有问题。

**Comment by sundy-li** [comment]
ios的问题待修复 (找机器调试中..)

**Comment by sundy-li** [comment]
已修复, 请更新最新版本
