### ISSUE TITLE
大神，请问这是啥问题？

### ISSUE THREAD

**Issue by ccgwork** [sundy-li/wechat_brain#19]
提问之前,请务必带有以下信息,不接受非技术性issue

1. 你运行的代码命令,你的操作是什么
go run cmd/main.go
2. 你的客户端操作系统, 微信版本, 是否添加成功证书
pc：win7-32 
手机：安卓
微信6.6.1
已添加证书
3. 执行的结果是什么
如图
![sundy-li](https://user-images.githubusercontent.com/35369195/34893138-e8809dd8-f816-11e7-9366-522aaad79a6e.png)

顺便弱弱的说一句，大神能不能出一个详细的安装配置教程啊？小白研究了一个通宵都还是没调试成功。5555

**Comment by mickeywaley** [comment]
WIN下直接运行  wechat_brain_0.13_windows_64-bit下的brain.exe就好了啊

![audj9yj kf9f0 2k bmrvps](https://user-images.githubusercontent.com/22206973/34900536-d9669710-f83b-11e7-8990-5e8ba868bc7f.png)
![i2wvbeygo x q db 19k](https://user-images.githubusercontent.com/22206973/34900537-d9945290-f83b-11e7-96f6-4574f53e8909.png)

**Comment by sundy-li** [comment]
@ccgwork  go环境的问题哈, sorry,忘了注明, 我用的是Go1.9,  req.URL.Hostname在低版本没有的.
你如果是go小白,可以参考 @mickeywaley 的截图方案, 直接安装对应的二进制文件
