### ISSUE TITLE
题库写死的？

### ISSUE THREAD

**Issue by fifa0329** [sundy-li/wechat_brain#2]
提问之前,请务必带有以下信息,不接受非技术性issue

1. 你运行的代码命令,你的操作是什么

2. 你的客户端操作系统, 微信版本, 是否添加成功证书

3. 执行的结果是什么

**Comment by sundy-li** [comment]
1. 已经做过的题目会自动存入数据库, 下次出现后显示 [标准答案]
2. 未做过的题目,通过搜索引擎API来做个统计概率显示,一定程度提高正确性
