### ISSUE TITLE
IOS 11.2.2测试成功，使用方法

### ISSUE THREAD

**Issue by norlover** [sundy-li/wechat_brain#22]
使用ios自带浏览器打开 证书进行安装
https://github.com/sundy-li/wechat_brain/raw/master/certs/goproxy.crt

然后IOS新版本 证书安装验证和证书信任是两个设置，并非安装验证后，就是信任，需要在关于本机中，找到证书信任设置 

![2](https://user-images.githubusercontent.com/5593700/34902845-48689082-f85f-11e7-8ddc-0319d322191e.png)

![1](https://user-images.githubusercontent.com/5593700/34902844-44e8986c-f85f-11e7-9573-ee4891171604.jpg)

**Comment by sundy-li** [comment]
安卓也要重新安装下证书

**Comment by chueia** [comment]
请问一下ios代理设置怎么弄？我在wifi代理里填上了pcIP和端口后就连不上小程序了

**Comment by HsiangHo** [comment]
@chueia 找到对应的WIFI链接，在WiFi详情里面有HTTP代理，设置你电脑对应的IP和端口就行。（要先安装证书哦）

**Comment by kxinds** [comment]
@chueia @sundy-li  IOS9.3.1设置wifi代理,同样连不上网络及abc.com(证书已安装)

**Comment by pyt618673** [comment]
各位大神～请问使用4G网络怎么设置代理啊？谢谢！
