### ISSUE TITLE
用了新的证书之后貌似安卓不能正常玩儿了

### ISSUE THREAD

**Issue by wjg1101766085** [sundy-li/wechat_brain#23]
如图所示~~

![_20180113134609](https://user-images.githubusercontent.com/10476982/34903233-389489f0-f868-11e7-9eb5-e7905c79c937.png)

**Comment by lonee8** [comment]
删除旧证书，加新证书。
不删也没事，就是没用了。

**Comment by wjg1101766085** [comment]
就是这样操作的！！
