### ISSUE TITLE
vps上怎么搭 centos 能写个命令不  技术小白

### ISSUE THREAD

**Issue by mickeywaley** [sundy-li/wechat_brain#25]
vps上怎么搭这个 能写个命令不  技术小白

系统: CentOS Linux 7.2.1511 (Core)

**Comment by lonee8** [comment]
编译个arm的，放路由器上了，爽。

**Comment by mickeywaley** [comment]
求教程

**Comment by sundy-li** [comment]
centos直接下载就行了啊,  wechat_brain_0.16_linux_64-bit.zip

**Comment by aroundtian** [comment]
centos上用源码执行go run cmd/main.go成功了。
不过想知道centos上怎么执行wechat_brain_0.16_linux_64-bit.zip中的brain文件，ssh中直接敲brain显示file not found；同样更希望能在arm平台的路由器上运行(linux)系统
请大神指点下 @sundy-li

**Comment by HsiangHo** [comment]
@aroundtian 先cd切换到对应目录，再执行对应的exec。

**Comment by aroundtian** [comment]
@HsiangHo 多谢回答，不过还是没成功，确定已切入目录，ls可看到brain文件

---------------------------------
[root /]# cd /root/wechat_brain_0-2
[root /root/wechat_brain_0-2]# ls
README.md
brain
questions.data

[root /root/wechat_brain_0-2]# brain
/bin/bash: brain: command not found

Exit code: 127

[root 
/root/wechat_brain_0-2]#

**Comment by HsiangHo** [comment]
@aroundtian 嗯，就是这样。  解决后记着close。

**Comment by aroundtian** [comment]
不是我open的issue哈 @HsiangHo

**Comment by lu-xu** [comment]
@lonee8 请问如何编译成在路由器运行的程序？有详细一点的步骤吗

**Comment by lonee8** [comment]
@lu-xu 先用我编译的这个吧。
和questions.data放到相同目录运行。
如果是远程管理的，可以用nohup ./main
[main.zip](https://github.com/sundy-li/wechat_brain/files/1630284/main.zip)

**Comment by lu-xu** [comment]
@lonee8 感谢，我研究下

**Comment by sundy-li** [comment]
跨平台编译arm版本,   `  GOARCH=arm GOOS=linux go build  -o brain cmd/main.go `
