### ISSUE TITLE
手机wifi设置代理为pc的ip和端口后就上不了网了

### ISSUE THREAD

**Issue by chueia** [sundy-li/wechat_brain#26]
手机是iphone6p
系统是最新
ip地址在百度上输入Ip查询出来的
端口地址是8998
手机和笔记本都连的同一个wifi，手机上代理设置输入pcIP和端口后就打不开小程序也上不了网，pc上的brain.exe也没反应

小白捣敲了蛮久一直卡在这里，希望能有大佬能提点一下

**Comment by mvpsky** [comment]
PC的IP地址是指内网IP，例如192.168.1.x 这种，不是百度查出来的公网IP

**Comment by Kwanloyal** [comment]
我的se，安装完证书设置完代理连不上网了
