### ISSUE TITLE
建议用CI来做自动合并题库

### ISSUE THREAD

**Issue by uoks** [sundy-li/wechat_brain#27]
类似我自己做的
https://github.com/uoks/wechat_brain/blob/travis/.travis.yml
再设个每天的Cron Jobs

当然如果监听issue的commit, 实时调用应该更好，不过travis似乎不支持

**Comment by sundy-li** [comment]
是的,之前考虑过travis, 但他是暂时不支持监听issue的,  也要开发脚本, 所以目前是crontab合并一次issue的file

**Comment by qinyang1018** [comment]
是否可以在增加一个第一次运行时  检查下题库是否有更新  如有就去自动下载覆盖 ，这样是不是能更方便些？  我不是写go的所以只是提个建议

**Comment by sundy-li** [comment]
@qinyang1018  @uoks 谢谢各位,   添加了merge.data文件来记录已经合并的文件, 另外配置travis了自动运行了, ok了~
