### ISSUE TITLE
答题结束会返回平局

### ISSUE THREAD

**Issue by sumpler** [sundy-li/wechat_brain#29]
1. 正常执行

2. ios，成功添加证书，可以正常接收到答案提示

3. 答题结束后会返回平局，可能由于官方更新识别到了异常。

**Comment by uoks** [comment]
感觉是网络问题，不是被识别了。 我也偶尔遇到

**Comment by sumpler** [comment]
确实如此，我也发现了，是超过几秒钟没有获取到结果就平局。
