### ISSUE TITLE
没反应

### ISSUE THREAD

**Issue by zky001** [sundy-li/wechat_brain#3]
提问之前,请务必带有以下信息,不接受非技术性issue

1. 你运行的代码命令,你的操作是什么
按照wiki来的操作，配置好了所有参数，使用8998端口，手机是http代理
2. 你的客户端操作系统, 微信版本, 是否添加成功证书
Macos10.13.2 微信是6.6.1 成功添加证书
3. 执行的结果是什么
微信小程序头脑王者其他都可以显示，就一部分不行。进入比赛后点击正确选项后要延迟5-7s的时间。

![screenshot_2018-01-09-15-11-32-774_](https://user-images.githubusercontent.com/9131265/34709354-dbc2ff54-f551-11e7-9d63-db9ad3df5b0e.png)
![screenshot_2018-01-09-15-11-35-305_](https://user-images.githubusercontent.com/9131265/34709360-e27857e0-f551-11e7-954e-70b8deb1cfb0.png)
![screenshot_2018-01-09-15-11-52-189_](https://user-images.githubusercontent.com/9131265/34709363-e752649a-f551-11e7-9e3e-0b19fe23596b.png)
![screenshot_2018-01-09-15-11-55-689_](https://user-images.githubusercontent.com/9131265/34709368-eb1dfac6-f551-11e7-8a1a-5dab9fd0baff.png)
![screenshot_2018-01-09-15-13-21-398_](https://user-images.githubusercontent.com/9131265/34709372-ef8c8abe-f551-11e7-87b3-69eff3b728af.png)

**Comment by zky001** [comment]
两种方式使用都可以跑起来，但是都是显示不全，没有反应，iOS和Android手机都不行。

**Comment by sundy-li** [comment]
`进入比赛后点击正确选项后要延迟5-7s的时间`  
因为是中间人截获了请求,所以延迟是正常的,  但正常情况延迟会在1-2s之间,由于有了延迟,所以代理是配置正常的

`微信小程序头脑王者其他都可以显示，就一部分不行`,   有没有显示出括号数字提示结果呢?    

这个问题可能和下午小程序更新有关 (我刚才测试了,好像没影响到我)   #4

**Comment by sundy-li** [comment]
我本地延迟挺低的, 云服务延迟也很低,  你可以试试    120.79.75.28:8998

**Comment by lu-xu** [comment]
已经配置了go环境，安装了证书，ip代理设置为本机ip端口8998
1.使用.exe程序，.data文件放到和exe同级目录，双击运行，出现如下报错
2018/01/11 10:04:54 server will at port:8998
2018/01/11 10:06:21 [004] WARN: Cannot handshake client www.googleapis.com:443 r
emote error: tls: unknown certificate
2018/01/11 10:06:21 [005] WARN: Cannot handshake client play.googleapis.com:443
remote error: tls: unknown certificate
2018/01/11 10:06:21 [008] WARN: Cannot handshake client play.googleapis.com:443
remote error: tls: unknown certificate
2018/01/11 10:06:27 [012] WARN: Cannot read TLS response from mitm'd server read
 tcp 192.168.199.219:60707->172.217.160.106:443: wsarecv: An existing connection
 was forcibly closed by the remote host.
2018/01/11 10:06:51 [014] WARN: Cannot handshake client www.googleapis.com:443 r
emote error: tls: unknown certificate
2.在repo目录使用命令 go run cmd/main.go，报错如下
$ go run cmd/main.go
api.go:8:2: cannot find package "github.com/PuerkitoBio/goquery" in any of:
        E:\Go\src\vendor\github.com\PuerkitoBio\goquery (vendor tree)
        E:\Go\src\github.com\PuerkitoBio\goquery (from $GOROOT)
        C:\Users\caobin\go\src\github.com\PuerkitoBio\goquery (from $GOPATH)
db.go:7:2: cannot find package "github.com/boltdb/bolt" in any of:
        E:\Go\src\vendor\github.com\boltdb\bolt (vendor tree)
        E:\Go\src\github.com\boltdb\bolt (from $GOROOT)
        C:\Users\caobin\go\src\github.com\boltdb\bolt (from $GOPATH)
spider.go:9:2: cannot find package "github.com/elazarl/goproxy" in any of:
        E:\Go\src\vendor\github.com\elazarl\goproxy (vendor tree)
        E:\Go\src\github.com\elazarl\goproxy (from $GOROOT)
        C:\Users\caobin\go\src\github.com\elazarl\goproxy (from $GOPATH)
cache.go:6:2: cannot find package "github.com/patrickmn/go-cache" in any of:
        E:\Go\src\vendor\github.com\patrickmn\go-cache (vendor tree)
        E:\Go\src\github.com\patrickmn\go-cache (from $GOROOT)
        C:\Users\caobin\go\src\github.com\patrickmn\go-cache (from $GOPATH)

**Comment by sundy-li** [comment]
@lu-xu  修复了编译的问题 ios的问题待修复 #6
