### ISSUE TITLE
可以把这个部署在服务器上吗？

### ISSUE THREAD

**Issue by qinyang1018** [sundy-li/wechat_brain#33]
我想部署在服务器上 然后通过代理连接服务器  这样就不需要一直在局域网连接电脑了 出门也可以使用了，这个方案是否可以行呢？

**Comment by sundy-li** [comment]
可以的, 我那个截图就是部署在云服务上的ip

**Comment by qinyang1018** [comment]
那是不是在云服务器上还要安装一个代理吗？  能给我方案吗？
