### ISSUE TITLE
下午版本更新后无法连接比赛

### ISSUE THREAD

**Issue by touzi** [sundy-li/wechat_brain#4]
2018/1/9 下午游戏更新了版本, 然后就不能连接进游戏了, 提示 1 重新连接

**Comment by sundy-li** [comment]
好的, 我看下, 可能游戏方知道了这种方式  作了防作弊..

**Comment by sundy-li** [comment]
目前我的 android版本还是可以继续玩的, 请问你的是ios的吗?

**Comment by touzi** [comment]
我的是 iOS 版本出现连接问题. 

 我 android 导入 crt 证书, pc dos 界面提示证书不受信.

**Comment by sundy-li** [comment]
pc dos界面是? 麻烦提供下截图看看

**Comment by shejianmin** [comment]
Cannot handshake client question.hortor.net:443 remote error: tls: unknown certificate authority

**Comment by touzi** [comment]
就是这个@shejianmin

**Comment by sundy-li** [comment]
有的手机设置页面操作一下,信任添加的证书

**Comment by touzi** [comment]
@sundy-li android 也需要吗, 我网上早半天没找到, 我是 T2

**Comment by sundy-li** [comment]
android应该不用的,  我在想怎么复现你们的问题, 我和我女朋友的android手机 工作还是正常的, 我去借多几个手机来试试 (暂时没其他手机)...

**Comment by touzi** [comment]
我明天在找找是不是证书问题, 我没搞过 android 证书

**Comment by Jortana** [comment]
进入游戏时提示网络不好 无法连接

**Comment by lyphol** [comment]
进去显示房间异常，请重新登陆

**Comment by sundy-li** [comment]
今天下午给朋友用了一下, 他的锤子手机, 还是可以正常工作的. 各位可以临时用我的云服务主机测试一下

120.79.75.28:8998

**Comment by Jortana** [comment]
iOS设备进去会显示网络不好
Android设备提示 101-:request:fall ssl hand shake error
用的是120.79.75.28:8998

**Comment by qwertccc** [comment]
可以用，安卓机器

**Comment by Jortana** [comment]
请问安卓机器怎么用 运行exe之后 wlan代理到pc吗 我这里进去之后所有图片都不显示也不显示推荐选项

Sent from my iPhone

On 10 Jan 2018, at 17:45, qwertccc <notifications@github.com<mailto:notifications@github.com>> wrote:


可以用，安卓机器

**Comment by sundy-li** [comment]
@Jortana  是啊, 设置代理为PC机器的, 我更新了README

**Comment by sundy-li** [comment]
已修复, 请更新最新版本
