### ISSUE TITLE
建议使用adb增加自动刷分的功能

### ISSUE THREAD

**Issue by chzeze** [sundy-li/wechat_brain#41]
提问之前,请务必带有以下信息,不接受非技术性issue

1. 你运行的代码命令,你的操作是什么

2. 你的客户端操作系统, 微信版本, 是否添加成功证书

3. 执行的结果是什么

**Comment by milkmeowo** [comment]
如果想自动刷分其实可以不需要用adb，直接提交答案，自动进房间，出房间，但是这样失去意义，如果需求人多倒是可以考虑实现一下

**Comment by Aliceniu** [comment]
我觉得也是，为啥不自动，自己刷太慢了

**Comment by chzeze** [comment]
使用adb可以直观的看到比赛的过程，也很爽，后台提交答案，直接刷分，看不到过程，就没什么意思了

**Comment by Aliceniu** [comment]
不过看多了也是没意思，最终不还是要刷分

**Comment by sundy-li** [comment]
从公平玩游戏来说, 这个工具是很evil的, 破坏了游戏的公平性,  也减少了娱乐的某种意义 ,或许过段时间这个游戏就不是很多人玩了, 直接刷分会让娱乐的意义变得更加微不足道, 所以就不加入了

**Comment by chzeze** [comment]
我写了一个改进的版本，增加了adb自动提交功能
https://github.com/chzeze/wetchat_brain
