### ISSUE TITLE
求32位的执行文件

### ISSUE THREAD

**Issue by ccgwork** [sundy-li/wechat_brain#45]
大神，能不能发布一个windows 32bit的wechat_brain_0.16_windows_64-bit.zip

**Comment by ccgwork** [comment]
wechat_brain_0.16_windows_64-bit.zip

**Comment by lu-xu** [comment]
[wechat_brain_0.16_windows_x86..zip](https://github.com/sundy-li/wechat_brain/files/1633865/wechat_brain_0.16_windows_x86.zip)
自己编译的，不知道行不行，你可以先拿去试试

**Comment by sundy-li** [comment]
`➜  wechat_brain git:(master) ✗ GOOS=linux GOARCH=386 go build -o brain_386 cmd/main.go`
`➜  wechat_brain git:(master) ✗ zip -r -o brain_386.zip brain_386`

[brain_386.zip](https://github.com/sundy-li/wechat_brain/files/1635571/brain_386.zip)

**Comment by sundy-li** [comment]
v0.17的最新版本,交叉编译教程 http://dmdgeeker.com/goBook/docs/ch01/cross_compile.html
