### ISSUE TITLE
无法链接 iCloud网关？

### ISSUE THREAD

**Issue by chp426** [sundy-li/wechat_brain#49]
IOS  成功运行过几次，但是现在运行的时候频繁提示2018/01/16 16:11:16 [116] WARN: Cannot handshake client gateway.icloud.com:443 EOF    是网络的问题吗？

**Comment by sundy-li** [comment]
这个应该不影响，手机某个程序在请求icloud，这个代理没代理过去

**Comment by chp426** [comment]
mac OS 系统，现在运行程序不是出现上面的代码就是压根没反应，刚刚全部重启了一边，把所有操作重新做了一遍还是这样...  不知道问题出在哪了...

**Comment by chp426** [comment]
现在没有提示 iCloud问题了，但是现在一直是无反应的状态，只有退出游戏的时候提示2018/01/16 17:23:22 [004] WARN: Websocket error: <nil>
2018/01/16 17:23:22 [004] WARN: Websocket error: read tcp 192.168.50.233:8998->192.168.50.138:52703: use of closed network connection

**Comment by sundy-li** [comment]
刚才头脑升级了, 刚刚提交了最新代码, 发布了新的版本, 兼容头脑王者的两个版本api, 这个问题应该修复了~
