### ISSUE TITLE
建议扩增题库

### ISSUE THREAD

**Issue by ihciah** [sundy-li/wechat_brain#5]
`GET /question/quiz/getCheckQuiz` 可以拿到随机的题目，第一个选项为正确答案

**Comment by sundy-li** [comment]
@ihciah  确实是个好办法, 但这样恶意请求有点担心被封...

**Comment by sundy-li** [comment]
![image](https://user-images.githubusercontent.com/3325189/34860259-443c1bfa-f797-11e7-89c1-698eaf395ae7.png)

这题库有点蛋疼...

**Comment by sundy-li** [comment]
#17
