### ISSUE TITLE
辅助已失效，暂时不可用

### ISSUE THREAD

**Issue by yqchen14** [sundy-li/wechat_brain#55]
链接https加密了，无法获取到题目，这个辅助怕是凉了

**Comment by lonee8** [comment]
貌似没加密。
修正一下格式就OK了

**Comment by lonee8** [comment]
修正 2处 /question/fight/findQuiz
为 /question/bat/findQuiz
就可以了。

**Comment by lonee8** [comment]
![qq 20180116194526](https://user-images.githubusercontent.com/19191933/34987353-d474f7b2-faf5-11e7-9fef-18a864ae3fea.jpg)
嘿嘿，一切j照旧

**Comment by wobocy** [comment]
楼上正解。handler文件修改一下就可以了

**Comment by sundy-li** [comment]
谁帮忙开个merge request，我合并下

**Comment by lonee8** [comment]
还能再懒点吗？
[spider.zip](https://github.com/sundy-li/wechat_brain/files/1634951/spider.zip)

**Comment by wobocy** [comment]
へ(゜∇、°)へ这个可以懒~ 手头没电脑

**Comment by sundy-li** [comment]
哈哈，我还在外面旅游，晚点我回去改下

**Comment by sundy-li** [comment]
各位试试看，刚刚手机端合并了一位朋友的提交

**Comment by zcxzhaojian** [comment]
IOS证书怎么安装，求详细教程

**Comment by sundy-li** [comment]
刚才头脑升级了, 刚刚提交了最新代码, 发布了新的版本, 兼容头脑王者的两个版本api, 这个问题应该修复了~

**Comment by zcxzhaojian** [comment]
@sundy-li 您好 加您QQ好友了 可以帮下忙吗

**Comment by sundy-li** [comment]
![image](https://user-images.githubusercontent.com/3325189/34995581-e09b7c2a-fb11-11e7-827a-5e1729db2f03.png)


已经手把手教会了楼上, 楼上的ios和我的安卓都可以用了, 大家更新v0.17版本就行了!

**Comment by KalChn** [comment]
今天更新过后打开辅助就无限掉线了，是我哪整错了吗？
