### ISSUE TITLE
高手些求教，IOS11.2.2 按着步骤做卡壳了

### ISSUE THREAD

**Issue by cnzhoujaing** [sundy-li/wechat_brain#58]
证书安装了，IP是写的是内网IP  端口也是8998  改成HTTP代理手机不能上网更别说连接游戏了，电脑端brain.exe打开什么样就一直是那样。

**Comment by wojs5** [comment]
证书信任没，在关于手机里

**Comment by cnzhoujaing** [comment]
- 
![img_0832](https://user-images.githubusercontent.com/35492213/34992097-f7aa27fa-fb06-11e7-9e6d-37262fc25509.PNG)
![img_0834](https://user-images.githubusercontent.com/35492213/34992098-f8819b22-fb06-11e7-8297-d54ae1376a8a.PNG)
![img_0835](https://user-images.githubusercontent.com/35492213/34992099-f8c7c804-fb06-11e7-94cc-38626529ac57.PNG)

信任了 不知道哪里错了

**Comment by wojs5** [comment]
spider.go里加行日志看看
func (s *spider) Init() {
	requestHandleFunc := func(request *http.Request, ctx *goproxy.ProxyCtx) (req *http.Request, resp *http.Response) {
		req = request
		**log.Println(ctx.Req.URL)**
		if ctx.Req.URL.Path == `/question/bat/findQuiz` {
			bs, _ := ioutil.ReadAll(req.Body)
			req.Body = ioutil.NopCloser(bytes.NewReader(bs))
			handleQuestionReq(bs)
		} else if ctx.Req.URL.Path == `/question/bat/choose` {

**Comment by zcxzhaojian** [comment]
楼上可以告诉我，证书怎么安装吗

**Comment by cnzhoujaing** [comment]
我是小白，那个GO用不来，用的是系统执行文件那个

**Comment by sundy-li** [comment]
各位, 头脑王者的服务端升级了接口, 麻烦更新到最新版本试试

**Comment by wojs5** [comment]
他是上不了网，接口变了应该也就没答案

**Comment by STDawn** [comment]
我的也是上不了网，求解

**Comment by touzi** [comment]
是否在同一个路由器下? @STDawn

**Comment by sundy-li** [comment]
#90
