### ISSUE TITLE
有被封号的吗？

### ISSUE THREAD

**Issue by yaoshanliang** [sundy-li/wechat_brain#59]

**Comment by zq1992zq2008** [comment]
没有

**Comment by lonee8** [comment]
有，我觉得我世界排名好像前进了。

**Comment by yqchen14** [comment]
这个辅助检测不出来的，封不了号。除非。。一堆人用一个服务器(比如题主的服务器)。。被封的是其他外挂，1分钟能自动上10星的，输了也加星66666

**Comment by qqnp1100** [comment]
胜率88%，目前没有被封

**Comment by gl09025** [comment]
失效了

**Comment by sundy-li** [comment]
这个工具只是获取请求返回 , 没有修改任何请求数据, 也没有自动模拟提交请求, 官方应该是难于识别成作弊的, 各位有遇到封号的情况吗?
