### ISSUE TITLE
ios11 头脑王者登录问题

### ISSUE THREAD

**Issue by KevinMyDing** [sundy-li/wechat_brain#6]
提问之前,请务必带有以下信息,不接受非技术性issue

1. 你运行的代码命令,你的操作是什么
直接执行
2. 你的客户端操作系统, 微信版本, 是否添加成功证书
ios11 微信版本 6.6.1 成功添加证书
3. 执行的结果是什么
登录时报错，错误如下：
手机截图：

![image](https://user-images.githubusercontent.com/10447540/34759691-a6e3e0e8-f617-11e7-9a90-97f68a51d151.png)

终端错误：
```shell
2018/01/10 14:54:41 server will at port:8998
2018/01/10 14:55:49 [003] WARN: Cannot handshake client question.hortor.net:443 EOF
2018/01/10 14:55:50 [004] WARN: Cannot handshake client question.hortor.net:443 EOF
2018/01/10 14:55:51 [005] WARN: Cannot handshake client question.hortor.net:443 EOF
2018/01/10 15:02:07 [008] WARN: Cannot handshake client question.hortor.net:443 EOF
2018/01/10 15:02:07 [009] WARN: Cannot handshake client question.hortor.net:443 EOF
2018/01/10 15:02:08 [010] WARN: Cannot handshake client question.hortor.net:443 EOF
2018/01/10 15:02:10 [011] WARN: Cannot handshake client question.hortor.net:443 EOF
```

不知道错误在哪里？

**Comment by yqchen14** [comment]
请问ios怎么添加crt证书？

**Comment by yqchen14** [comment]
我也是同样的错误  ios11  此服务器的证书无效。您可能正在连接到一个伪装成“question.hortor.net"的服务器

**Comment by sundy-li** [comment]
ios确实有问题, 但我没有机器来调试..  (各位可以帮忙调试修复下这个问题吗?)

**Comment by yqchen14** [comment]
@ sundy-li  ios导入证书之后，我这里的证书显示是授信状态的，但是依旧有问题。看来不是授信的问题

**Comment by yqchen14** [comment]
@sundy-li  ios10.3之后，证书信任设置位置更改了，需要到设置-通用-关于手机-证书信任设置 里面开启授信，然后就可以使用了，这个问题解决了，麻烦更新一下readme

**Comment by yqchen14** [comment]
ios10.3的证书授信路径是-设置-通用-关于本机-证书信任设置，  设置证书授信之后，不会再出现题主所示的证书验证错误，取而代之的是不断跳出”提示：1  重新连接“

**Comment by yugai** [comment]
不会go，跪求修复iOS重连问题。

**Comment by yqchen14** [comment]
看到另一位大神的相同项目，里面提到了ios的问题:
"goproxy 无法代理 websocket 导致IOS无法使用代理进入游戏"
 @sundy-li 对于go不了解，可否参照如下解决问题？
https://github.com/zxb19890727/websocket_agent#websocket_transfer

**Comment by lonee8** [comment]
代理设置没什么问题。
但
可能是app不同，格式小有不同吧。
ios进答题界面一直弹  提示1

**Comment by sundy-li** [comment]
@yqchen14  谢谢, 我去解决下这个问题

**Comment by sundy-li** [comment]
已修复, 请更新最新版本
