### ISSUE TITLE
ios 安装和信任证书后，设置代理后连不上网

### ISSUE THREAD

**Issue by STDawn** [sundy-li/wechat_brain#60]
提问之前,请务必带有以下信息,不接受非技术性issue

1. 你运行的代码命令,你的操作是什么  设置代理

2. 你的客户端操作系统, 微信版本, 是否添加成功证书   

iOS 11.12,微信6.6.1

3. 执行的结果是什么

无法联网，更别说连小程序

**Comment by sundy-li** [comment]
你好, 如果不能上网,  你看看是不是网络通不了,尝试以下两种测试方法之一
1.当前网络环境下可以用安卓试试能不能使用成功.
2.你试试用其他代理工具 (charles, fiddle, wireshark,anyproxy等试试能不能抓包成功)

**Comment by sundy-li** [comment]
ios需要信任证书, #64
