### ISSUE TITLE
封号啦啦啦

### ISSUE THREAD

**Issue by ccgwork** [sundy-li/wechat_brain#61]
刚上王者就被封了？！这GR的怎么查到的？大家小心拉！~~
![screenshot_2018-01-17-14-59-27](https://user-images.githubusercontent.com/35369195/35031025-309eac44-fb9c-11e7-9ee3-c7e9c7ab63a3.jpg)

**Comment by Leohc92** [comment]
你确定你是被封了么？

**Comment by ccgwork** [comment]
![qq 20180117154728](https://user-images.githubusercontent.com/35369195/35031593-93e47e80-fb9e-11e7-826a-5a5d44922201.jpg)
提示网络不给力！

为了防止TX的人进来，加了马赛克

**Comment by Leohc92** [comment]
@ccgwork 那就是你的网络不给力而已啊

**Comment by ccgwork** [comment]
不是吧，换了几个网都这样，晚上回去试试。但愿……

**Comment by tiny656** [comment]
昨天尝试用了一下，下一次登录也给了作弊检测的提示。再接下来，也是一直提示网络问题，这个功能就用不了了

**Comment by sundy-li** [comment]
~~ 好像在打击作弊了..

**Comment by HsiangHo** [comment]
@sundy-li  是啊，所以我觉得要提高使用门槛吧，就像隔壁同类开源代码一样，非程序员还搞不定。

**Comment by wobocy** [comment]
是提示打击了，不过使用正常也没被封，还是不要太贪婪吧，差不多得了。昨天刚把程序改了自动答题，瞬间感觉看它自己浪(＊￣︶￣＊)有点无聊了

**Comment by HsiangHo** [comment]
@wobocy 岂不是盘盘1200分？  建个小号上王者！

**Comment by hujinhu** [comment]
@wobocy   分享一下自动答题的

**Comment by sundy-li** [comment]
这个工具只是获取请求返回 , 没有修改任何请求数据, 官方应该是难于识别成作弊的, 各位有遇到封号的情况吗?

**Comment by tiny656** [comment]
@sundy-li 没遇到被封，只是后面工具不起作用了

**Comment by wobocy** [comment]
@HsiangHo 请关注大佬 chzeze先发布的改进版  https://github.com/chzeze/wetchat_brain

**Comment by wobocy** [comment]
昨晚50自动刷到100星，被退出登录两次，使用倒正常

**Comment by newljs** [comment]
服务器挂了
