### ISSUE TITLE
证书无效啦

### ISSUE THREAD

**Issue by ziyanziyu** [sundy-li/wechat_brain#62]
![image](https://user-images.githubusercontent.com/7148309/35037134-8199e1d0-fbb1-11e7-9047-eea91cba0179.png)

![image](https://user-images.githubusercontent.com/7148309/35037151-96c06110-fbb1-11e7-8539-0f74b78e5683.png)

**Comment by sundy-li** [comment]
麻烦更新下最新版本, 重新安装证书

**Comment by 1076383223** [comment]
我想删除这个证书，应该怎么做
