### ISSUE TITLE
ios 11.2.2 运行报错如图

### ISSUE THREAD

**Issue by Jortana** [sundy-li/wechat_brain#64]
![image](https://user-images.githubusercontent.com/29514716/35085740-f19c8b5a-fc64-11e7-892d-535bc7c78f50.png)

**Comment by jyiL** [comment]
![image](https://user-images.githubusercontent.com/19472992/35089776-e6f76c0c-fc72-11e7-934d-18ffcd1bf789.png)
![image](https://user-images.githubusercontent.com/19472992/35089807-f6063246-fc72-11e7-9986-be7957a7d594.png)
我也是ios11.2.2

**Comment by Kwanloyal** [comment]
我的11.1居然网都连不上

**Comment by sundy-li** [comment]
各位, 十分抱歉, ios的问题暂时可能解决不了, 还缺对应的设备来调试...

**Comment by fengqiangboy** [comment]
设置->通用->关于->证书信任设置  信任一下证书即可

**Comment by jyiL** [comment]
@fengqiangboy 信任证书后可以了，但是那个题库有好多错误答案

**Comment by sundy-li** [comment]
看来ios可以用,先close这个issue
