### ISSUE TITLE
IOS如何安装证书

### ISSUE THREAD

**Issue by Shinerain** [sundy-li/wechat_brain#69]
提问之前,请务必带有以下信息,不接受非技术性issue

1. 你运行的代码命令,你的操作是什么
安装证书步骤不理解

2. 你的客户端操作系统, 微信版本, 是否添加成功证书
IOS 如何添加证书 abc.com要怎么才能访问

3. 执行的结果是什么

**Comment by HsiangHo** [comment]
方法1： 设置好HTTP代理，然后访问abc.com安装证书，然后再信任证书。
方法2：通过MacBook的Airdrop功能直接分享到手机，并安装信任。

@Shinerain

**Comment by sundy-li** [comment]
参考下 #90
