### ISSUE TITLE
邪门儿了，死活不上分

### ISSUE THREAD

**Issue by qwertccc** [sundy-li/wechat_brain#7]
用是能用，就是用了这个吧，绝对比别人出手慢，每次都是双方回答全对，但是对方手快就赢了。。。

就这样儿，我已经输了8000多金币，现在已经0金币不能玩儿了

囧。。。。。。我勒个去，我就实在不明白，难道是系统抓住了？对手都是电脑？里外里反正份儿比你高？这是什么鬼。。。

我那8000多的金币真是我手打一点儿一点儿赢起来的啊。。。就这么就全干了。。。。。。。哭死了

**Comment by yqchen14** [comment]
问一下ios的crt证书是怎么导入的

**Comment by qwertccc** [comment]
我安卓的。。。

**Comment by yqchen14** [comment]
是不是你的网络延时太高了，如果代理延迟超过5s，答两题才等于别人一题，确实容易输

**Comment by qwertccc** [comment]
主要问题我感觉这个“别人”就是电脑

理由1：这玩意儿有可能全对1次，有可能2次，对方把把都是全对这是什么鬼！？

理由2：我也全对的时候，对方还都比我快，比我快1次可以，，，2次也忍了，把把都这样儿是什么鬼？！

**Comment by qwertccc** [comment]
北京时间21点，这个游戏挂了，是不是访问太多？还是有人批量扒题库呢

**Comment by sundy-li** [comment]
听别人说有镜像人, 我去试试有木有你这种情况
 服务端嗅探不到你用了代理, 代理是会有延迟的,不过我用代理电脑延迟1-2s左右, 130盘高胜率到王者了..

**Comment by sundy-li** [comment]
@qwertccc  如果网络慢,可以试试我的云主机代理  120.79.75.28:8998 , 近期都可以用(已经帮5位同学上了王者了)

**Comment by qwertccc** [comment]
@sundy-li 哥们儿我网应该不错啊，联通光纤有外网IP，独立带宽200m，路由是k3官方改版固件，手机和电脑都是5g的wifi连接。。。

**Comment by qwertccc** [comment]
我刚刚自己玩儿了1000多金币了，准备再试试挂，预备翻身：D

**Comment by qwertccc** [comment]
玩儿了俩钟头，没遇到无敌的“对手”

好了~~~
