### ISSUE TITLE
比技术重要的问题，能否把软件介绍讲清楚，标准是正常理解能力的人

### ISSUE THREAD

**Issue by taijifeifei** [sundy-li/wechat_brain#70]
这个程序看起来好生敬佩，只是软件说明往好听的说是思维跳跃性大……
举两个例子：
1,通篇没有软件运行设备的介绍，读者读起说明完全靠推理。
2,第一段，安装证书，手机浏览器如何，读者应当推测在手机上运行。
3,第二段，设置代理，突然杀出个“代理ip为个人pc的ip”，读者正常推测除了手机还需一台pc运行程序，ip是局域网ip还是internetip，先推测是外网ip吧。
4,第三段，运行，方式一下载软件“压缩后”，推测是笔误理解为“解压后”吧。
下载到哪，现在读者脑中有两个设备手机和pc，看看系统没有android，正常推测下载到电脑吧。
说明让下载questions.data，无链接，读者必将问道去哪里下载，靠推测是不行了。
5,打开微信程序，读者脑子还是手机和电脑，这次推测是手机打开微信程序吧。
6，然后说明是成功运行，如果以上推理的都正确，是不是理解为手机和电脑无需adb链接，好厉害。
7,好吧找数据库，哪个是，好吧，推测是最后一个陌生人的上传的是。
作者，您的软件厉害，可以说给您写软件说明的那个网友，从第一句开始，就没给过一句明确的意思表示，让人句句推测。

**Comment by wobocy** [comment]
@taijifeifei 实不相瞒这个说明是我改的，您说的这个确实存在，里面有个顺序也有问题，但是我好懒啊 ´◡`

**Comment by sundy-li** [comment]
抱歉，文档写的确实不是很明确，我今晚回去就补充下文档，尽量写的思路条例清晰，方便接入

**Comment by sundy-li** [comment]
稍微完善了下, 明天再来优化下

**Comment by taijifeifei** [comment]
作者改的好清理，让人一眼就知道如何操作，我是没看明白没办法帮着写，就算看明白了，也没法写的像作者这么清理。
