### ISSUE TITLE
ubuntu 16.04 go 1.9.2 无法运行main.go

### ISSUE THREAD

**Issue by Feb17** [sundy-li/wechat_brain#71]
root@ubuntu:~/go/src/wechat_brain# go run cmd/main.go
cmd/main.go:7:2: cannot find package "github.com/sundy-li/wechat_brain" in any of:
	/root/go/src/wechat_brain/vendor/github.com/sundy-li/wechat_brain (vendor tree)
	/usr/local/go/src/github.com/sundy-li/wechat_brain (from $GOROOT)
	/root/go/src/github.com/sundy-li/wechat_brain (from $GOPATH)

环境变量的问题？求教 第一次用go语言

**Comment by Feb17** [comment]
root@ubuntu:~/go/src/wechat_brain# go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
这是环境变量信息

**Comment by wobocy** [comment]
按提示建俩文件夹就行了

**Comment by Feb17** [comment]
@wobocy 感谢 已解决

**Comment by Fomovet** [comment]
@Feb17 如何解决的？我也卡在这里了

**Comment by sundy-li** [comment]
源码要放在目录 $GOPATH/src/github.com/sundy-li/ 下

**Comment by Fomovet** [comment]
@sundy-li 明白，已经解决了！
