### ISSUE TITLE
ios设置代理后无法访问abc.com安装证书

### ISSUE THREAD

**Issue by liuxu379** [sundy-li/wechat_brain#79]

**Comment by sundy-li** [comment]
1. 设置代理后 可以访问其他网站吗?
2. 访问abc.com 提示什么?

手动传证书过去可以安装吗?

**Comment by liuxu379** [comment]
@sundy-li 无法访问任何网站。ios无法直接打开.crt证书，只能通过safari来安装。我把证书放入本地web服务器内进行安装的。

**Comment by sundy-li** [comment]
应该是ios访问不到abc.com #90
