### ISSUE TITLE
合并题库出现The system cannot find the path specified

### ISSUE THREAD

**Issue by Roywaller** [sundy-li/wechat_brain#80]
`handling sundy-li https://github.com/sundy-li/wechat_brain/files/1650596/questions.zip
2018/01/23 10:49:24 Error open /tmp/questions.zip: The system cannot find the path specified.
handling Roywaller https://github.com/sundy-li/wechat_brain/files/1650642/questions.zip
2018/01/23 10:49:26 Error open /tmp/questions.zip: The system cannot find the path specified.
handling jianghwjx https://github.com/sundy-li/wechat_brain/files/1650932/questions.zip
2018/01/23 10:49:27 Error open /tmp/questions.zip: The system cannot find the path specified.
handling Auska https://github.com/sundy-li/wechat_brain/files/1650969/questions.data.zip
2018/01/23 10:49:29 Error open /tmp/questions.zip: The system cannot find the path specified.
handling Fetter-poi https://github.com/sundy-li/wechat_brain/files/1651798/questions.zip
2018/01/23 10:49:30 Error open /tmp/questions.zip: The system cannot find the path specified.
handling jianghwjx https://github.com/sundy-li/wechat_brain/files/1651951/questions.zip
2018/01/23 10:49:32 Error open /tmp/questions.zip: The system cannot find the path specified.
handling sundy-li https://github.com/sundy-li/wechat_brain/files/1654230/questions.data.zip
2018/01/23 10:49:34 Error open /tmp/questions.zip: The system cannot find the path specified.`

**Comment by sundy-li** [comment]
路径在/tmp, 试试 mkdir -p /tmp/

**Comment by Roywaller** [comment]
windows环境出现这个问题 linux环境没问题

**Comment by boyyao** [comment]
windows下需要吧tmp变量从/tmp改成 ./tmp

**Comment by Roywaller** [comment]
谢谢可以了
