### ISSUE TITLE
 IOS今天连不上头脑服务器

### ISSUE THREAD

**Issue by kkLee** [sundy-li/wechat_brain#82]
IOS 版本：11.2.2
2部iphone 6(系统版本11.2.2)  ，iphone X (系统版本11.2.2)  都是这个错误。我也用安卓，一样的情况。

一个回合掉1次。

**Comment by kkLee** [comment]
IOS 能连上了，安装了之后需要再设置一次信任证书，

具体如下：

设置--通用--关于本机--证书信任设置--(对应证书的开关)。

不过还是会频繁掉线，基本上衣个回合掉一次。

**Comment by keitaking** [comment]
应该是更新了吧

**Comment by kkLee** [comment]
是的，谢谢，服务器又关了，我以为是我的问题。

**Comment by keitaking** [comment]
估计小程序更新完辅助软件也要更新

**Comment by sundy-li** [comment]
ios今天升级
