### ISSUE TITLE
两种模式都不能用了

### ISSUE THREAD

**Issue by princeliebe** [sundy-li/wechat_brain#85]
模式一之前还能用，模式二一直不起作用。
![default](https://user-images.githubusercontent.com/35736236/35284644-2faf9d7a-0010-11e8-92d2-8397dd3b684c.jpg)

**Comment by sundy-li** [comment]
我这还可以用啊, 你开了代理吗?

**Comment by SoYeonQwQ** [comment]
可以用..

**Comment by liviolei** [comment]
可以用，证书没装对

**Comment by princeliebe** [comment]
是，如@liviolei说的，证书没装对。第一次安装的时候vpn&app、wifi，两种方式我都安装了，所以能用。后来更新版本，安装证书我只装了vpn&app，就不行，需要安装wifi那个选项。
现在可以了。谢谢大家！
上传题库以表歉意。
