### ISSUE TITLE
mac  ios 使用不正常

### ISSUE THREAD

**Issue by 599070001** [sundy-li/wechat_brain#88]
2018/01/24 14:48:11 [243] WARN: Cannot handshake client question.hortor.net:443 EOF
2018/01/24 14:48:12 [244] WARN: Cannot handshake client question.hortor.net:443 EOF
2018/01/24 14:48:13 [245] WARN: Cannot handshake client question.hortor.net:443 EOF
2018/01/24 14:48:24 [249] WARN: Cannot handshake client question.hortor.net:443 EOF
2018/01/24 14:48:25 [250] WARN: Cannot handshake client question.hortor.net:443 EOF
2018/01/24 14:48:26 [251] WARN: Cannot handshake client question.hortor.net:443 EOF
2018/01/24 14:48:29 [253] WARN: Cannot handshake client question.hortor.net:443 EOF
2018/01/24 14:48:30 [254] WARN: Cannot handshake client question.hortor.net:443 EOF
2018/01/24 14:48:31 [255] WARN: Cannot handshake client question.hortor.net:443 EOF

证书也有正常安装

我的android 是正常的

**Comment by happyuanhao** [comment]
兄dei没有添加信任的缘故，关于手机，最下面信任设置，马上更新了趁现在速度了。

**Comment by 599070001** [comment]
老铁，没毛病，就是这个问题

**Comment by 599070001** [comment]
给个建议，当题目出现“不”字的时候，推荐答案需要反选，不然设计逻辑存在问题

**Comment by sundy-li** [comment]
否定逻辑, 大家肉眼判断哈~

**Comment by happyuanhao** [comment]
三点20更新了 现在好像不能用了。

**Comment by sundy-li** [comment]
android还可以用啊, ios不知道..

**Comment by happyuanhao** [comment]
还能用，我搞错了，目前发现一个问题，就是错题有点多，标注了标准答案，却是错误答案。

**Comment by sundy-li** [comment]
ios证书问题看下这位朋友的描述   #90
