### ISSUE TITLE
出题速度时快时慢

### ISSUE THREAD

**Issue by mengboy** [sundy-li/wechat_brain#89]
有时候出题目的时候时间直接是剩7s了。
有时候答题，在点完选项之后，会卡住到剩大概1s的时候才结算。
一局里面大概会有2次这样的情况发生，并且在命令行出现Saving的时候，很大几率出现卡主的现象，有没有大佬遇到一样的情况？

**Comment by 599070001** [comment]
是你电脑配置太低了吧

**Comment by SoYeonQwQ** [comment]
在哪跑的,我在Google cloud和阿里云跑都没问题,1核2g

**Comment by sundy-li** [comment]
saving在存入本地数据库, 不过写的数据很小, 除非磁盘很慢, 一般不受影响

**Comment by mengboy** [comment]
发现啦，是我路由器配置的问题，把路由器重置一下OK了，谢谢各位，么么哒。
