### ISSUE TITLE
怎么把我本地的题库递交给你？

### ISSUE THREAD

**Issue by qwertccc** [sundy-li/wechat_brain#9]
rt

尽点儿力。。。

**Comment by wjg1101766085** [comment]
老铁。发一份儿怎么样啊？？

**Comment by wjg1101766085** [comment]
![qq 20180111132158](https://user-images.githubusercontent.com/10476982/34809800-6c21cdce-f6d2-11e7-9008-33d86a1c76fd.png)

**Comment by lonee8** [comment]
做一个合并工具吧，大家都提交。

**Comment by sundy-li** [comment]
我做一个合并工具吧,  自动合并多份题库

**Comment by sundy-li** [comment]
@wjg1101766085 
1. 如果 发一份到这个issues, 我需要写个脚本去定期merge, 这个有点麻烦, 后面我可能会考虑
2. 目前采用merge request 来合并,操作如下

- 合并后,提交一个merge request给我,我将合并题库
```
	➜  wechat_brain git:(master) ✗ files=`ls /data/tmp/questions*`
	➜  wechat_brain git:(master) ✗ echo $files
	/data/tmp/questions.data
	➜  wechat_brain git:(master) ✗ go run cmd/question_utils.go -a merge  -fs "$files"
	2018/01/11 20:01:23 merged file /data/tmp/questions.data
	2018/01/11 20:01:23 merged 4286 questions
	2018/01/11 20:01:23 total questions => 4286
	➜  wechat_brain git:(master) ✗

```

**Comment by yudianguo** [comment]
用那个release里面的mac版本，找不到你这个文件呢
➜  wechat_brain git:(master)  files=`ls /data/tmp/questions*`
zsh: no matches found: /data/tmp/questions*

**Comment by sundy-li** [comment]
@yudianguo  这个文件就是你们自己的题库意思, 待合并文件

**Comment by Yanshuaibing** [comment]
请问下题库格式是什么样的？

**Comment by Yanshuaibing** [comment]
比如问题是：
{"data":{"quiz":"世界著名的枪械制造商「格洛克」公司，是哪个国家的？","options":["德国","澳大利亚","奥地利","美国"],"num":5,"school":"文科","type":"军事","contributor":"凯瑞丹","endTime":1515734954,"curTime":1515734939},"errcode":0}
答案是：
{"data":{"uid":0,"num":5,"answer":3,"option":3,"yes":true,"score":400,"totalScore":1020,"rowNum":5,"rowMult":1.4,"costTime":0,"roomId":56950346,"enemyScore":180,"enemyAnswer":0},"errcode":0}
我应该怎么写到文件里？

**Comment by sundy-li** [comment]
自动写到文件中的, 当前路径的questions.data中

**Comment by sundy-li** [comment]
#17   为了方便大家, 不用提交merge request了 ,  大家来这里提交吧,用文件方式

**Comment by yanbinA** [comment]
[questions.zip](https://github.com/sundy-li/wechat_brain/files/1773932/questions.zip)
