### ISSUE TITLE
登录成功，但是进入匹配对战失败

### ISSUE THREAD

**Issue by dingjianjaja** [sundy-li/wechat_brain#93]
一直运行十多局正常，突然掉线，再次登录后无法匹配，停留在匹配页面等待

**Comment by dingjianjaja** [comment]
其他都ok，微信收发消息正常。就是这个游戏无法登录

**Comment by dingjianjaja** [comment]
Mac 在运行过程中如何查看请求参数和返回结果

**Comment by sundy-li** [comment]
@dingjianjaja 最后面那条是
docker容器已经在跑了..
